name: filcnaplo
description: 'Nem hivatalos e-napló alkalmazás az e-Kréta rendszerhez'
version: 2.1.0-pre1+49

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.1
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.0
  feather_icons_flutter: ^4.7.4
  flutter_typeahead: ^1.8.1
  file_picker: ^1.9.0
  package_info: ^0.4.0
  intl: ^0.16.0
  flutter_linkify: ^3.1.3
  url_launcher: ^5.4.10
  flutter_html: ^1.0.0
  share: ^0.6.5
  sqflite: ^1.3.0
  permission_handler: ^5.0.0
  path_provider: ^1.6.9
  tinycolor: ^1.0.2
  open_file: ^3.0.1
  background_fetch: ^0.5.6
  circular_reveal_animation: ^1.1.5
  flutter_speed_dial:
    git:
      url: https://github.com/irasekh3/flutter_speed_dial
      ref: master
  image_cropper: ^1.2.3
  charts_flutter: ^0.9.0
  flutter_material_color_picker: ^1.0.5
  flutter_swiper: ^1.1.6
  in_app_review: ^0.2.0
  pdf: ^1.11.1
  printing: ^3.6.1
  photo_view: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/page1.png
    - assets/page2.png
    - assets/page3.png
    - assets/page4.png
    - assets/wave1.png
    - assets/wave2.png
    - assets/wave3.png
    - assets/wave4.png
    - assets/Roboto-Regular.ttf

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans/GoogleSans-Regular.ttf
        - asset: fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 700
        - asset: fonts/GoogleSans/GoogleSans-Italic.ttf
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          style: italic
          weight: 500

    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono/SpaceMono-Bold.ttf
          weight: 700
        - asset: fonts/SpaceMono/SpaceMono-Italic.ttf
          style: italic
        - asset: fonts/SpaceMono/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay/RedHatDisplay-Regular.ttf
        - asset: fonts/RedHatDisplay/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: fonts/RedHatDisplay/RedHatDisplay-Italic.ttf
          style: italic
        - asset: fonts/RedHatDisplay/RedHatDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/RedHatDisplay/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: fonts/RedHatDisplay/RedHatDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/RedHatDisplay/RedHatDisplay-Black.ttf
          weight: 800
        - asset: fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          style: italic
          weight: 800
        